export const ERRORS = {
  INVALID_USER_NAME: "El nombre de usuario es inválido",
  INVALID_EMAIL: "El correo es inválido",
  INVALID_FIRST_NAME: "El primer nombre es inválido",
  INVALID_LAST_NAME: "El apellido es inválido",
  SHORT_PASSWORD: "La contraseña debe ser mayor a 8 caracteres",
  LONG_PASSWORD: "La contraseña debe ser menor a 60 caracteres",
  TOO_YOUNG: "La edad del usuaio debe ser mayor a 13 años",
  TOO_OLD: "La edad del usuario debe ser menor a 125 años",
  EMAIL_IN_USE: "Un usuario ya está usando tu correo",
  USER_NAME_IN_USE: "Un usuario está usando tu nombre",
  INCORRECT_PASSWORD: "Contraseña incorrecta",
  INCORRECT_EMAIL: "Ningun usuario esta registrado con el correo ingresado",
  FIRST_NAME_CONTAINS_OFFENSIVE_WORDS: "El primer nombre contiene palabras ofensivas",
  LAST_NAME_CONTAINS_OFFENSIVE_WORDS: "El segundo nombre contiene palabras ofensivas",
};
